### ISSUE TITLE
Unclosed file warnings when calling sifdecode

### ISSUE THREAD

**Issue by jfowkes** [jfowkes/pycutest#11]
Currently on Python 3 we get the following warnings whenever sifdecode is called:

```
test_sifdecode_extras.py:21: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
build_interface.py:333: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
```

I've traced it to the `p = subprocess.Popen(...)` lines in `sifdecode_extras.py` and `build_interface.py`, however doing the sensible thing and using `with subprocess.Popen(...) as p:` fixes the warnings on Python 3 but breaks sifdecode on Python 2:
https://travis-ci.org/github/jfowkes/pycutest/jobs/673033735

Any thoughts on this? I'm confused.

**Comment by lindonroberts** [comment]
Interesting, I've not seen those Python3 warnings at all on Linux (but happy to try and get rid of them)!

There seem to be 2 errors coming up in Python 2.7:

1. Local variable 'messages' not found in decode_and_compile_problem: here, I think we need to define `messages` before the `with subprocess.popen(...) as p` block, so its scope is outside that. However, a better approach would be to define `msg_lines = []` before that block, and move `msg_lines = messages.splitlines()` inside the block, since then if everything fails we can still loop sensibly over `msg_lines` when printing output.

2. The name `FileNotFoundError` is not known. This seems to be a Python 2 problem where it should be `IOError`. There is a workaround here: https://github.com/Sarcasm/compdb/issues/5

Otherwise, a hack solution is to have a check for Python 2 vs Python 3 (`sys.version_info.major`) and have different code for both cases.

**Comment by jfowkes** [comment]
Thanks for looking into this! I have tried your suggestions:

1. While this resolves the variable not found error, the main issue is still there: sifdecode simply does not appear to run on Python 2 using the `with open as` construct (the messages are all empty, hence the initial 'variable undefined' message).  

2. Defining `FileNotFoundError` as `OSError` (since `os.getcwd()` returns `OSError` not `IOError` on Python 2 for some reason) resolves this name not defined error.

I'm still really confused as to why using `with subprocess.popen(...) as p` means sifdecode appears just not to run on Python 2 but runs fine on Python 3.

**Comment by lindonroberts** [comment]
It does seem like #1 is weird. A bit more searching found this: https://stackoverflow.com/questions/44609582/popen-differences-between-python-2-and-3/44610028#44610028

Perhaps we need to have `messages = p.stdout.read().decode()`? Apparently Python 3 uses byte encoding of process stdout information, but Python 2 uses text encoding?

The other option seems to be setting `universal_newlines=True` in the call to `subprocess.Popen(...)` (see here: https://stackoverflow.com/questions/30279846/subprocess-works-in-python-2-but-not-in-python-3).

**Comment by jfowkes** [comment]
Managed to track down the error: using `with subprocess.popen(...) as p` actually throws an `AttributeError: __exit__`  since `subprocess.Popen` on Python 2 doesn't support the `with as` syntax, see: https://bugs.python.org/issue13202

So back to square one, I guess we need another way of handling this.

**Comment by lindonroberts** [comment]
That's very annoying, as there's basically nothing we can do with that. Perhaps the easiest solution is to have some repeated code and a `if sys.version_info.major >= 3` (it's not nice, but I don't know there's much we can do given that `__exit__` issue)

**Comment by jfowkes** [comment]
Turns out there was an easy fix after all: simply closing stdout after reading it :see_no_evil:
