### ISSUE TITLE
Problem with PyCUTEst.find_problems()

### ISSUE THREAD

**Issue by Learn2Solve** [jfowkes/pycutest#37]
**Describe the bug**
When I tried to find problems as the tutorial using
probs = pycutest.find_problems(constraints='unconstrained', userN=True), I got the following error message.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/scratch/szhao89/optim/lib/python3.8/site-packages/pycutest/sifdecode_extras.py", line 294, in find_problems
    data=problem_properties(name)
  File "/local/scratch/szhao89/optim/lib/python3.8/site-packages/pycutest/sifdecode_extras.py", line 234, in problem_properties
    'origin': cfDict['origin'][cfString[5].upper()],
KeyError: 'S'

However, other functions work. For example, I can run 
p = pycutest.import_problem('ROSENBR').

**Information about your installation:**
I just followed the instruction to install cutest and compile it. 

Thanks for your help!

**Comment by jfowkes** [comment]
@Learn2Solve this is indeed due to a malformed classification string in `DMN15102LS.SIF`

I have requested a fix from upstream, in the meantime you can correct this locally by changing line 19 of `DMN15102LS.SIF` (located in your MASTSIF folder) to read:
```
*   classification SUR2-MN-66-4643
```
which is the correct classification string for that CUTEst problem.

**Comment by Learn2Solve** [comment]
@jfowkes  It works! Thanks so much!
