### ISSUE TITLE
Issues with setting problem dimension

### ISSUE THREAD

**Issue by hjmshi** [jfowkes/pycutest#4]
I'm currently not able to set the problem dimension in the sifParams option for some of the CUTEst problems. When trying to set N to be 500 for the SROSENBR problem, I receive the following error:

```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    problem = utils.CUTEstProblem(args.problem_name, args.N, args.print_sif, args.eps_f, args.eps_g)
  File "/home/hjmshi/BFGS_with_Errors/utils.py", line 46, in __init__
    self.problem = pycutest.import_problem(problem_name, sifParams=self.sif_params)
  File "/home/hjmshi/anaconda3/lib/python3.6/site-packages/pycutest/build_interface.py", line 328, in import_problem
    objList = decode_and_compile_problem(problemName, destination, sifParams, sifOptions, quiet)
  File "/home/hjmshi/anaconda3/lib/python3.6/site-packages/pycutest/build_interface.py", line 206, in decode_and_compile_problem
    raise RuntimeError('SIFDECODE error: %s' % param_error)
RuntimeError: SIFDECODE error:  Failed setting N to 500
```

I've tried clearing the cache but it doesn't help. I've checked to make sure that this is an sifParams option using the `print_available_sif_params` function, which gives this: 
```
Parameters available for problem SROSENBR:
N/2 = 5 (int, n = 10 original value)
N/2 = 25 (int, n = 50)
N/2 = 50 (int, n = 100)
N/2 = 250 (int, n = 500)
N/2 = 500 (int, n = 1000)
N/2 = 2500 (int, n = 5000) [default]
N/2 = 5000 (int, n = 10000)
End of parameters for problem SROSENBR
```

Could I get some help on where to start debugging this? Thanks in advance!

**Comment by jfowkes** [comment]
Many thanks for reporting! This is a bug on our side: when we create CUTEst problem subfolders in the cache folder, we append the parameters (if there are any) to the folder name. Unfortunately, as `N/2` is the parameter name for `SROSENBR`, we try to create the folder `SROSENBR_N/2500` which is not a valid folder name as it contains the special character `/`. 

Until we fix this, I suggest the following workaround: edit `SROSENBR.SIF` in your `$MASTSIF` folder so that the parameter you want is the *only one that is unstarred* (this will make it the default):  
```
*   N/2 is half the number of variables

*IE N/2                 5              $-PARAMETER n = 10     original value
*IE N/2                 25             $-PARAMETER n = 50
*IE N/2                 50             $-PARAMETER n = 100
*IE N/2                 250            $-PARAMETER n = 500
*IE N/2                 500            $-PARAMETER n = 1000
 IE N/2                 2500           $-PARAMETER n = 5000
*IE N/2                 5000           $-PARAMETER n = 10000
```
For example, in the above N/2=2500 is the default. You can then call `pycutest.import_problem('SROSENBR')` and it will compile with the default parameter you just set. 

@lindonroberts: any thoughts on how we could fix this? Linux does not allow `/` in folder names :(

**Comment by lindonroberts** [comment]
When we have parameters, the folder name is based on the problem plus the result of the function params_to_string() in build_interface.py. Modified to drop '/', and replace digits with test.

For example, now SROSENBR with sifParams={'N/2':250} is saved in cache folder "SROSENBR_Ntwo250".
